# Configuration for Supabase project

project_id = "completion-2.0"

[functions.generateAgoraToken]
verify_jwt = false
entrypoint = "./functions/generateAgoraToken/index.ts"

[functions.notifyIncomingCall]
verify_jwt = true
entrypoint = "./functions/notifyIncomingCall/index.ts"

[functions.sync-driver-to-primary]
verify_jwt = true
entrypoint = "./functions/sync-driver-to-primary/index.ts"
